qemu-kvm: implement debug mode and fix option parsing bug
It was not correct to shift after `-n` was parsed.

Since `-net user` is specified using configuration file, no need
to also have the `-n` option for that. Instead, use `-n` to indicate
that we don't actually want to run qemu, just to do a dry run.

diff --git a/qemu-kvm b/qemu-kvm
--- a/qemu-kvm
+++ b/qemu-kvm
@@ -1,7 +1,12 @@
 #!/bin/sh
 # Public domain, 2012-2014 Simone Basso <bassosimone@gmail.com>
 
-OPTIONS=""
+prefix=/var/local/qemu-kvm
+
+ECHO=""
+OPTIONS="-enable-kvm -runas nobody -daemonize -chroot $prefix/jail"
+QEMU=`which qemu-system-x86_64`
+SUDO=`which sudo`
 USAGE="usage: qemu-kvm [-bns] [-d display] [-i cdrom] machine"
 
 ARGS=$(getopt bd:i:ns $*)
@@ -22,23 +27,22 @@ while [ $# -gt 0 ]; do
         OPTIONS="$OPTIONS -cdrom $1"
         shift
     elif [ "$OPT" = "-n" ]; then
-        OPTIONS="$OPTIONS -net user"  # override default net settings
-        shift
+        ECHO="echo"
     elif [ "$OPT" = "-s" ]; then
         OPTIONS="$OPTIONS -snapshot"
     elif [ "$OPT" = "--" ]; then
         break
     else
         echo "FATAL: option parsing error" 1>&2
+        echo $USAGE 1>&2
         exit 1
     fi
 done
 if [ $# -ne 1 ]; then
+    echo "FATAL: missing machine name"
     echo $USAGE 1>&2
     exit 1
 fi
-
-prefix=/var/local/qemu-kvm
 
 if [ ! -r $prefix/etc/$1 ]; then
     echo "FATAL: machine not configured" 1>&2
@@ -49,21 +53,18 @@ fi
 
 # Note: add at the beginning so we can override using cmdline
 if [ "$NIC_MODEL" != "user" ]; then
-    MAC=$(echo $1.varanasy.polito.it | md5sum | \
-      sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/02:\1:\2:\3:\4:\5/')
+    if [ "$MAC" = "auto" ]; then
+        MAC=$(echo $1.varanasy.polito.it | md5sum | \
+          sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/02:\1:\2:\3:\4:\5/')
+    fi
     OPTIONS="-net nic,model=$NIC_MODEL,macaddr=$MAC $OPTIONS"
     OPTIONS="-net tap,script=$prefix/bin/ifup.$BRIDGE $OPTIONS"
 else
     OPTIONS="-net user $OPTIONS"
 fi
+OPTIONS="-drive file=$prefix/disk/$1.raw,index=0,media=disk,if=$DRIVE_IF $OPTIONS"
+OPTIONS="-m $MEMORY $OPTIONS"
+OPTIONS="-vga $VGA $OPTIONS"
 
 # XXX I don't remove the iptables rules
-/usr/bin/sudo /usr/bin/qemu-system-x86_64                               \
-    -enable-kvm                                                         \
-    -drive file=$prefix/disk/$1.raw,index=0,media=disk,if=$DRIVE_IF     \
-    -m $MEMORY                                                          \
-    -vga $VGA                                                           \
-    -daemonize                                                          \
-    -chroot $prefix/jail                                                \
-    -runas nobody                                                       \
-    $OPTIONS
+$ECHO $SUDO $QEMU $OPTIONS
